from pathlib import Path
import logging

logger = logging.getLogger(__name__)

CLINERULES_FILENAME = ".clinerules"


def _detect_stack(repo_path: Path) -> str:
    """Detect primary stack from repo root files."""
    if (repo_path / "pyproject.toml").exists() or (repo_path / "requirements.txt").exists():
        return "python"
    if (repo_path / "package.json").exists():
        return "node"
    if (repo_path / "Cargo.toml").exists():
        return "rust"
    return "generic"


def _generate_clinerules(repo_path: Path, stack: str) -> str:
    """Generate .clinerules content appropriate to the detected stack."""
    test_cmd = {
        "python": "uv run pytest --tb=no -q",
        "node": "npm test",
        "rust": "cargo test --quiet",
        "generic": "run your test suite",
    }.get(stack, "run your test suite")

    return f"""# .clinerules — auto-generated by ClineMCP ensure_clinerules
# Review and adjust before relying on this file.
# Stack detected: {stack}

## TASK PHRASING RULES
1. Execute tool calls immediately — never describe them.
2. One action per iteration. Do not plan multiple steps.
3. Read before write — always read the target file before modifying it.
4. Output format must be explicit — no preamble, no code blocks unless asked.
5. Stop when the task is complete — do not suggest follow-up actions.
6. File paths are relative to cwd unless the task specifies otherwise.
7. When a task says "do not explain" — zero explanation, one line output only.

## VERIFICATION
Run `{test_cmd}` after every file change.
Report the exact pass/fail count. Do not proceed if tests fail.

## CLINE-ELIGIBLE TASKS
- Single file modifications with clear completion criteria
- Adding one function or class to an existing file
- Writing tests for a specific existing function
- Updating a config, schema, or constants file
- Small bug fixes in a single function

## DEVIN-ONLY TASKS
- New module or package creation
- Multi-file refactors
- Architectural decisions
- Anything requiring judgment across the codebase
- Tasks with ambiguous completion criteria
"""


def ensure_clinerules(repo_path: str) -> dict:
    """
    Check for .clinerules in repo_path. Generate if missing.

    Returns:
        dict with keys: repo_path, existed, path, content, stack
    """
    path = Path(repo_path)

    if not path.exists() or not path.is_dir():
        return {
            "repo_path": repo_path,
            "existed": False,
            "path": None,
            "content": None,
            "stack": None,
            "error": f"repo_path does not exist or is not a directory: {repo_path}"
        }

    clinerules_path = path / CLINERULES_FILENAME

    if clinerules_path.exists():
        logger.info(f"ensure_clinerules.exists: {repo_path}")
        return {
            "repo_path": repo_path,
            "existed": True,
            "path": str(clinerules_path),
            "content": clinerules_path.read_text(encoding="utf-8"),
            "stack": None,
            "error": None
        }

    stack = _detect_stack(path)
    content = _generate_clinerules(path, stack)
    clinerules_path.write_text(content, encoding="utf-8")
    logger.info(f"ensure_clinerules.generated: {repo_path}, stack={stack}")

    return {
        "repo_path": repo_path,
        "existed": False,
        "path": str(clinerules_path),
        "content": content,
        "stack": stack,
        "error": None
    }
